# Generated by Django 5.0.6 on 2024-06-29 07:29

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo', '0002_crimereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='complaint_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Under Review', 'Under Review'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Received', max_length=20),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
