# Generated by Django 5.0.6 on 2024-06-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo', '0003_crimereport_complaint_id_crimereport_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='user_agent',
            field=models.CharField(default='', max_length=255),
        ),
    ]
