# Generated by Django 5.0.6 on 2024-06-29 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odoo', '0005_alter_crimereport_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimereport',
            name='user_agent',
        ),
    ]
