# Generated by Django 5.0.6 on 2024-06-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo', '0006_remove_crimereport_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='user_agent',
            field=models.CharField(default='', max_length=255),
        ),
    ]
